import { ArrowRight, CalendarCheck, LogIn, ShieldCheck, UsersRound } from 'lucide-react'

function Welcome() {
  return <main className="min-h-screen bg-[#e9eee8] px-5 py-6 text-[#24313b] md:px-10 md:py-10">
    <div className="mx-auto flex min-h-[calc(100vh-3rem)] max-w-300 flex-col justify-between">
      <header className="flex items-center justify-between"><div className="flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#24313b] text-sm font-extrabold text-white">K</span><span><strong className="block font-['Manrope'] text-base tracking-tight">kinship</strong><small className="block text-[10px] uppercase tracking-[0.2em] text-[#7b887e]">people ops</small></span></div><div className="flex items-center gap-2 text-xs font-bold text-[#718078]"><ShieldCheck size={15} /> Sistem internal HR</div></header>
      <section className="grid items-center gap-12 py-12 lg:grid-cols-[0.95fr_1.05fr] lg:py-0">
        <div className="max-w-xl"><p className="mb-5 text-xs font-bold uppercase tracking-[0.2em] text-[#66806d]">Selamat datang di Kinship</p><h1 className="font-['Manrope'] text-4xl font-extrabold leading-[1.08] tracking-[-0.04em] md:text-6xl">Satu ruang untuk <span className="text-[#6f9278]">menjaga tim</span> tetap selaras.</h1><p className="mt-6 max-w-md text-sm leading-6 text-[#718078]">Pilih layanan yang ingin kamu gunakan untuk melanjutkan ke ruang kerja HR atau mencatat kehadiran hari ini.</p><div className="mt-8 flex items-center gap-3 text-xs font-semibold text-[#7d8b81]"><UsersRound size={17} className="text-[#52705e]" /> Kelola people ops dengan lebih sederhana</div></div>
        <div className="grid gap-4 sm:grid-cols-2"><a href="/dashboard" className="group rounded-4xl bg-[#24313b] p-6 text-white shadow-[0_24px_70px_rgba(36,49,59,0.18)] transition hover:-translate-y-1 hover:bg-[#344753] md:p-8"><div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-white/10 text-[#d9eadc]"><LogIn size={22} /></div><p className="mt-10 text-xs font-bold uppercase tracking-[0.16em] text-[#aebbb4]">Untuk HR & admin</p><h2 className="mt-3 font-['Manrope'] text-2xl font-extrabold">Login ke Dashboard</h2><p className="mt-3 text-sm leading-6 text-[#b9c5bd]">Lihat ringkasan, karyawan, kehadiran, cuti, dan penggajian.</p><span className="mt-8 flex items-center gap-2 text-sm font-extrabold text-[#d9eadc]">Masuk sekarang <ArrowRight size={16} className="transition group-hover:translate-x-1" /></span></a><a href="/absensi" className="group rounded-4xl border border-white/80 bg-[#fbfaf6] p-6 shadow-[0_24px_70px_rgba(56,76,61,0.1)] transition hover:-translate-y-1 md:p-8"><div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-[#e8eee8] text-[#52705e]"><CalendarCheck size={22} /></div><p className="mt-10 text-xs font-bold uppercase tracking-[0.16em] text-[#a1a19d]">Untuk semua karyawan</p><h2 className="mt-3 font-['Manrope'] text-2xl font-extrabold">Absensi Karyawan</h2><p className="mt-3 text-sm leading-6 text-[#718078]">Catat jam masuk dan pulang dengan cepat dari portal absensi.</p><span className="mt-8 flex items-center gap-2 text-sm font-extrabold text-[#52705e]">Buka absensi <ArrowRight size={16} className="transition group-hover:translate-x-1" /></span></a></div>
      </section>
      <footer className="flex flex-col gap-2 text-[11px] text-[#87938a] sm:flex-row sm:items-center sm:justify-between"><span>© 2026 Kinship People Ops</span><span>Akses aman untuk operasional internal</span></footer>
    </div>
  </main>
}

export default Welcome
