import { useMemo, useState } from 'react'
import { BriefcaseBusiness, CalendarDays, ChevronRight, Filter, Mail, MoreHorizontal, Plus, Search, Sparkles, Users, X } from 'lucide-react'
import { candidates } from '../../data/dummy'

const stageStyles = { New: ['#eb765c', '#c95840'], Review: ['#6b76d8', '#5961b7'], Interview: ['#d49329', '#aa741e'], Offer: ['#53a879', '#39865e'] }
const stageLabels = { New: 'Baru', Review: 'Ditinjau', Interview: 'Wawancara', Offer: 'Penawaran' }
const stats = [['Lowongan terbuka', '12', '+2 bulan ini', BriefcaseBusiness], ['Kandidat aktif', '48', '+14%', Users], ['Wawancara minggu ini', '16', '4 hari ini', CalendarDays], ['Rata-rata waktu perekrutan', '24 hari', '-18% dari bulan lalu', Sparkles]]

function Dashboard({ activeNav, flash }) {
  const [selected, setSelected] = useState(candidates[0])
  const [query, setQuery] = useState('')
  const [stage, setStage] = useState('Semua tahap')
  const [showAdd, setShowAdd] = useState(false)
  const filteredCandidates = useMemo(() => candidates.filter((candidate) => `${candidate.name} ${candidate.role}`.toLowerCase().includes(query.toLowerCase()) && (stage === 'Semua tahap' || stageLabels[candidate.stage] === stage)), [query, stage])

  return <div className="mx-auto max-w-360 px-5 py-7 md:px-10 md:py-9">
    <div className="mb-8 flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><div className="mb-2 flex items-center gap-2 text-xs font-bold text-[#a1a19d]"><span>RUANG KERJA</span><ChevronRight size={13} /><span className="text-[#53615d]">{activeNav.toUpperCase()}</span></div><h2 className="font-['Manrope'] text-3xl font-extrabold tracking-[-0.04em] md:text-[38px]">Rekrutmenmu, <span className="text-[#718b79]">terus bergerak.</span></h2><p className="mt-2 max-w-lg text-sm text-[#858b88]">Jaga tim tetap selaras dan setiap kandidat terus melangkah.</p></div><button type="button" onClick={() => setShowAdd(true)} className="flex w-fit items-center gap-2 rounded-xl bg-[#24313b] px-4 py-3 text-sm font-bold text-white"><Plus size={17} /> Tambah kandidat</button></div>

    <section className="mb-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{stats.map(([label, value, sub, Icon], index) => <div key={label} className={`animate-rise delay-${index} rounded-2xl border border-[#e9e5dc] bg-[#fbfaf6] p-5`}><div className="flex items-start justify-between"><p className="text-xs font-bold text-[#8c928f]">{label}</p><div className="rounded-lg bg-[#e8eee8] p-2 text-[#52705e]"><Icon size={16} /></div></div><div className="mt-4 flex items-baseline gap-2"><p className="font-['Manrope'] text-3xl font-extrabold">{value}</p><span className="text-[11px] font-bold text-[#5f9270]">{sub}</span></div></div>)}</section>

    <section className="grid gap-6 xl:grid-cols-[minmax(0,1.55fr)_minmax(330px,0.8fr)]"><div className="rounded-2xl border border-[#e9e5dc] bg-[#fbfaf6] p-5 md:p-6"><div className="mb-5 flex items-center justify-between"><div><h3 className="font-['Manrope'] text-lg font-extrabold">Alur kandidat</h3><p className="mt-1 text-xs text-[#929793]">Pantau setiap kandidat di seluruh lowonganmu.</p></div><button type="button" onClick={() => flash('Tampilan alur siap diperbarui')} className="flex items-center gap-1 text-xs font-bold text-[#68746e]"><Filter size={14} /> Sesuaikan tampilan</button></div><div className="mb-5 flex flex-col gap-3 sm:flex-row"><div className="relative flex-1"><Search size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-[#a7aba7]" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Cari kandidat..." className="w-full rounded-xl border border-[#e6e2d9] bg-[#fffefa] py-2.5 pl-9 pr-3 text-xs outline-none" /></div><select value={stage} onChange={(event) => setStage(event.target.value)} className="rounded-xl border border-[#e6e2d9] bg-[#fffefa] px-3 py-2.5 text-xs font-semibold text-[#68716e] outline-none"><option>Semua tahap</option>{Object.values(stageLabels).map((label) => <option key={label}>{label}</option>)}</select></div><div className="mb-4 flex items-center justify-between border-b border-[#eeeae1] pb-3 text-[10px] font-bold uppercase tracking-[0.14em] text-[#adafa9]"><span>{filteredCandidates.length} kandidat</span><button type="button" onClick={() => { setQuery(''); setStage('Semua tahap') }} className="flex items-center gap-1 normal-case tracking-normal text-[#7e8982]">Hapus filter <X size={12} /></button></div><div className="space-y-1">{filteredCandidates.map((candidate) => { const [dot, text] = stageStyles[candidate.stage]; return <button type="button" key={candidate.name} onClick={() => setSelected(candidate)} className={`flex w-full items-center gap-3 rounded-xl p-3 text-left transition hover:bg-[#f4f3ed] ${selected.name === candidate.name ? 'bg-[#f1f3ee]' : ''}`}><div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-full text-xs font-bold" style={{ backgroundColor: candidate.color }}>{candidate.initials}</div><div className="min-w-0 flex-1"><p className="truncate text-sm font-bold">{candidate.name}</p><p className="mt-0.5 truncate text-xs text-[#969b97]">{candidate.role}</p></div><div className="hidden items-center gap-2 sm:flex"><span className="h-2 w-2 rounded-full" style={{ backgroundColor: dot }} /><span className="text-xs font-semibold" style={{ color: text }}>{stageLabels[candidate.stage]}</span></div><span className="hidden w-12 text-right text-xs font-bold text-[#68746e] md:block">{candidate.score}%</span><MoreHorizontal size={17} className="text-[#b0b2ad]" /></button> })}</div></div>

      <div className="rounded-2xl border border-[#e9e5dc] bg-[#24313b] p-6 text-[#f7f5ef]"><div className="mb-7 flex items-center justify-between"><p className="text-[10px] font-bold uppercase tracking-[0.18em] text-[#aebbb4]">Sorotan kandidat</p><MoreHorizontal size={18} className="text-[#aebbb4]" /></div><div className="flex items-center gap-3"><div className="flex h-14 w-14 items-center justify-center rounded-full text-sm font-bold text-[#53615d]" style={{ backgroundColor: selected.color }}>{selected.initials}</div><div><h3 className="font-['Manrope'] text-lg font-extrabold">{selected.name}</h3><p className="mt-0.5 text-xs text-[#abb7b0]">{selected.role}</p></div></div><div className="mt-6 grid grid-cols-2 gap-y-4 border-y border-white/10 py-5"><div><p className="text-[10px] uppercase tracking-wider text-[#8f9d96]">Skor kecocokan</p><p className="mt-1 text-xl font-bold text-[#c9e0ce]">{selected.score}%</p></div><div><p className="text-[10px] uppercase tracking-wider text-[#8f9d96]">Didaftarkan</p><p className="mt-1 text-sm font-semibold">{selected.applied}</p></div><div><p className="text-[10px] uppercase tracking-wider text-[#8f9d96]">Lokasi</p><p className="mt-1 text-sm font-semibold">{selected.location.split(',')[0]}</p></div><div><p className="text-[10px] uppercase tracking-wider text-[#8f9d96]">Tahap</p><p className="mt-1 text-sm font-semibold">{stageLabels[selected.stage]}</p></div></div><p className="mt-5 text-xs leading-5 text-[#b9c2bc]">{selected.note}</p><div className="mt-5 flex flex-wrap gap-2">{selected.tags.map((tag) => <span key={tag} className="rounded-md bg-white/10 px-2 py-1 text-[10px] font-semibold text-[#d2dbd4]">{tag}</span>)}</div><button type="button" onClick={() => flash(`Email untuk ${selected.name} siap dikirim`)} className="mt-7 flex w-full items-center justify-center gap-2 rounded-xl bg-[#d9eadc] py-2.5 text-xs font-extrabold text-[#31563e]"><Mail size={14} /> Hubungi</button></div></section>

    <section className="mt-6 grid gap-6 md:grid-cols-2"><div className="rounded-2xl border border-[#e9e5dc] bg-[#fbfaf6] p-5"><h3 className="font-['Manrope'] text-base font-extrabold">Wawancara mendatang</h3>{[['10:00', 'Raka Pratama', 'Frontend Engineer'], ['13:30', 'Alya Rahma', 'People Operations'], ['09:00', 'Dimas Arya', 'Product Manager']].map(([time, name, role]) => <div key={name} className="flex items-center gap-3 border-t border-[#eeeae1] py-3"><span className="w-11 text-xs font-bold text-[#76817b]">{time}</span><div className="h-7 w-7 rounded-full bg-[#d8e4db]" /><div><p className="text-xs font-bold">{name}</p><p className="text-[11px] text-[#9a9f9a]">{role}</p></div></div>)}</div><div className="rounded-2xl border border-[#e9e5dc] bg-[#eef3ee] p-5"><h3 className="font-['Manrope'] text-base font-extrabold">Kondisi tim</h3><div className="mt-6 flex items-end gap-3"><span className="font-['Manrope'] text-4xl font-extrabold text-[#42634b]">84</span><span className="mb-1 text-xs font-bold text-[#6e8975]">/ 100 sehat</span></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-[#d7e2d8]"><div className="h-full w-[84%] rounded-full bg-[#72a27b]" /></div></div></section>

    {showAdd && <div className="fixed inset-0 z-30 flex items-center justify-center bg-[#24313b]/30 p-4 backdrop-blur-sm"><div className="w-full max-w-md rounded-2xl bg-[#fbfaf6] p-6 shadow-2xl"><div className="mb-5 flex items-start justify-between"><div><h3 className="font-['Manrope'] text-xl font-extrabold">Tambah kandidat</h3><p className="mt-1 text-xs text-[#929793]">Buat profil kandidat baru.</p></div><button type="button" onClick={() => setShowAdd(false)} aria-label="Tutup dialog"><X size={18} /></button></div><div className="space-y-3"><input placeholder="Nama lengkap" className="w-full rounded-xl border border-[#e4e1d8] bg-white p-3 text-sm" /><input placeholder="Alamat email" className="w-full rounded-xl border border-[#e4e1d8] bg-white p-3 text-sm" /></div><button type="button" onClick={() => { setShowAdd(false); flash('Kandidat berhasil ditambahkan') }} className="mt-5 flex w-full items-center justify-center gap-2 rounded-xl bg-[#24313b] py-3 text-sm font-bold text-white"><Plus size={16} /> Tambahkan ke alur</button></div></div>}
  </div>
}

export default Dashboard